language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: pJLrXRbBT9AfZ5RjPTBvzwGnDezW9042ZDvlWn5ySHcKa8iaWGb4PLounWkRjki7u87gwnwp1Ce3zssr+EVOAxmJ9GuLdagUBEDjLk4WjfTD7QlmQ4cjVMdd4HB++OGS0fLelGk8exX3BPtYf4AwWl2cHLS3ALaivXFiHLX2kj1hizL//TcdlGbHBbpOwp3dkMPf08XVjX4tpjAKvsZs3EE6srggzWj+WrCoEOHFIvRp0mXqGpISXhCcd3k+4fm9In5nRZSTplInZDGZZF4KpS29tSYU7YrxAoFU0IJwWGZDleCmjMuQ73zXokMtkVllVJkpaEb7r+Sb0gQsmnEL2Y7EjTxWL0yXQ7fCVX/rbhg9HCLHOv4bjOmhqlCqOK3Vf9mruoe82BQcRdLNqC1X4Gl0schIRYeZkoIbGAy+TqU3aiagbl7bjV9eo//n4XGPpbu/2aTcwU2tep0MmPf3efQtk0lIDpimDiHza+FZ1bMFf1LXnACh7EDGoNVSLUyXgXvPKjRAxvaKis9U2MiXMNWgsjb/U7ib/Shgmc3nzHt9gXYRzJwIBJNXlLfXICaOf0V6S2yaoXSmYuzJs9MIGtoWIxypMi6sxyvCPOg6YPh36lYyYpQl6yc6xA5nJx5hYXlqrSZjAL8YCSibYWKSUtRzdluhw2FFhmwhzChhETo=
  app: obscure-springs-35933
  on:
    repo: khriskempis/inventoryManagement
